// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/15/2024, 1:12:12 AM
const configMerger = require("C:/Users/night/Desktop/weatherApp/weather-app/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/night/Desktop/weatherApp/weather-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/night/Desktop/weatherApp/weather-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/night/Desktop/weatherApp/weather-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/night/Desktop/weatherApp/weather-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/night/Desktop/weatherApp/weather-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/night/Desktop/weatherApp/weather-app/plugins/**/*.{js,ts,mjs}","C:/Users/night/Desktop/weatherApp/weather-app/composables/**/*.{js,ts,mjs}","C:/Users/night/Desktop/weatherApp/weather-app/utils/**/*.{js,ts,mjs}","C:/Users/night/Desktop/weatherApp/weather-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/night/Desktop/weatherApp/weather-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/night/Desktop/weatherApp/weather-app/app.config.{js,ts,mjs}"] }));

module.exports = config
